### ISSUE TITLE
Database Todo Model Validations

### ISSUE THREAD

**Issue by dagher41** [aaronjohnscott/TodoList#9]
Let's define some validations on our model so that we don't save bad data

- [ ] dueDate has to be in the future
- [ ] priority has to be greater than or equal to 0
- [ ] name has to be at least 3 characters long

The todo should fail to save in the database if it fails to meet any of these conditions. (https://mongoosejs.com/docs/validation.html)
